[package]
name = "mobius"
version = "0.1.0"
edition = "2021"

[dependencies]
abstraction = { path = "../abstraction" }
svg = "0.18.0"

[dev-dependencies]
test-case = "3.3.1"
pretty_assertions = "1.4.1"
